name: demandium_serviceman
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.3
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  geolocator: ^8.2.1
  url_launcher: ^6.1.3
  country_code_picker: ^2.0.2
  phone_number: ^0.12.0+2
  webview_flutter: ^3.0.4
  pin_code_fields: ^7.4.0
  flutter_widget_from_html_core: ^0.8.5+3
  flutter_typeahead: ^4.0.0
  pointer_interceptor: ^0.9.3+2
  shimmer_animation: ^2.1.0+1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  firebase_core:
  firebase_messaging:
  expandable: ^5.0.1
  fl_chart: ^0.55.0
  dotted_border: ^2.0.0+2
  flutter_local_notifications: ^9.5.3+1
  timelines: ^0.1.0
  file_picker: ^4.6.1
  pdf: ^3.1.0
  open_file_safe: ^3.2.3
  flutter_downloader: ^1.8.3
  permission_handler: ^10.0.0
  flutter_html: ^3.0.0-alpha.1
  printing: ^5.9.3
  change_app_package_name: ^1.1.0
  firebase_auth: ^3.1.1
  flutter_launcher_icons: ^0.9.2


dependency_overrides:
  firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/font/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/Ubuntu-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/serviceman_app.png"
